ALTER TABLE doctors ADD COLUMN gst_number VARCHAR(255) NULL;
ALTER TABLE doctors ADD COLUMN pan_number VARCHAR(255) NULL;
ALTER TABLE doctors ADD COLUMN address VARCHAR(500) NULL;
ALTER TABLE doctors ADD COLUMN registration_no VARCHAR(255) NULL;
ALTER TABLE doctors ADD COLUMN education VARCHAR(500) NULL;
ALTER TABLE doctors ADD COLUMN document_url VARCHAR(500) NULL;
